[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Sub-Threshold Standard Cell Design"
authors = [{name = "Karthik B K", email = "bkkarthik@pesu.pes.edu"}]
dynamic = ["version", "description"]
